export const strings = {
  "tog": "TOG",
  "walkthrough_subtitle": "Helping you Do more TOGether when you want to...",
  "login_facebook": "Log in with Facebook",
  "explore_features": "Explore Features",
  "i_want_to": "I want to ",
  "create": "create",
  "my_activities": "my activities",
  "browse": "browse",
  "send": "send",
  "edit": "edit",
  "hello": "hello",
  "what": "What",
  "where": "Where",
  "when": "When",
  "who": "Who",
};
